services:
  gateway:
    container_name: gateway
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    build:
      context: docker
      dockerfile: gateway.dockerfile

  app:
    container_name: app
    build:
      context: .
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health_check || exit 1"]
      interval: 1s
      timeout: 2s
      retries: 10
    volumes:
      - "./sqlite.db:/app/sqlite.db"
